---
- hosts: localhost
  tags: always
  become: true #enables sudu

  pre_tasks:
  #  - name: pre-run | update package cache (debian, etc)
  #    tags: always
  #    apt: update_cache=yes
  #    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]
     - name: print
       ansible.builtin.debug:
         msg:
           - '{{ user_directory }}'
           - '{{ username }}'
           - '{{ ansible_distribution }}'

          #- name: .bashrc file
    #copy:
            #src: files/bashrc
      #dest: '{{ user_directory }}/.bashrc'
      #owner: '{{ username }}'
      #    group: '{{ username }}' 
# run roles
#
- hosts: localhost
  tags: base
  become: true
  roles:
    - base

- hosts: localhost
  tags: desktop
  become: true
  roles:
    - desktop
  
- hosts: localhost
  tags: development
  become: true
  roles:
    - development
