---
- hosts: localhost
  connection: local
  become: true #enables sudu

  tasks:
  - name: install htop
    package:
      name: 
        - htop
        - valgrind

  - name: .bashrc file
    copy:
      src: files/bashrc
      dest: /home/kobi_medrish/.bashrc
      owner: kobi_medrish
      group: kobi_medrish 

