---
- hosts: localhost
  tags: always
  become: true #enables sudu

  pre_tasks:
  #  - name: pre-run | update package cache (debian, etc)
  #    tags: always
  #    apt: update_cache=yes
  #    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]
     - name: print
       ansible.builtin.debug:
         msg:
           - '{{ user_directory }}'
           - '{{ username }}'
           - '{{ ansible_distribution }}'

     - name: Add moolticute PPA
       apt_repository: 
         repo: 'ppa:mooltipass/moolticute'
         state: present
         update_cache: yes
         validate_certs: False


     - name: Add cherytree PPA
       apt_repository:
         repo: 'ppa:giuspen/ppa'
         state: present
         update_cache: yes
         validate_certs: False
 
     - name: Add cryptomator PPA
       apt_repository:
         repo: 'ppa:sebastian-stenzel/cryptomator'
         state: present
         update_cache: yes
         validate_certs: False

     - name: Add ondrej PHP PPA
       apt_repository:
         repo: 'ppa:nginx/stable'
         state: present
         update_cache: yes
         validate_certs: False

  tasks:
          #- name: Add moolticute ppa
          #apt_repository: repo='ppa:mooltipass/moolticute' state=present
          #update_cache: yes

      #- name: Add cherrytree ppa
      #ansible.builtin.apt_repository:
      #repo: ppa:giuspen/ppa

      #  - name: Add cryptomator ppa
      #ansible.builtin.apt_repository:
      #repo: ppa:sebastian-stenzel/cryptomator      

          #- name: .bashrc file
    #copy:
            #src: files/bashrc
      #dest: '{{ user_directory }}/.bashrc'
      #owner: '{{ username }}'
      #    group: '{{ username }}' 
# run roles
#
- hosts: localhost
  tags: base
  become: true
  roles:
    - base
  
- hosts: localhost
  tags: development
  become: true
  roles:
    - development
