---
- hosts: localhost
  tags: always
  become: true #enables sudu

  pre_tasks:
  #  - name: pre-run | update package cache (debian, etc)
  #    tags: always
  #    apt: update_cache=yes
  #    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]
     - name: print
       ansible.builtin.debug:
         msg:
           - '{{ user_directory }}'
           - '{{ username }}'
           - '{{ ansible_distribution }}'
  tasks:
          #- name: Add moolticute ppa
          #apt_repository: repo='ppa:mooltipass/moolticute' state=present
          #update_cache: yes

      #- name: Add cherrytree ppa
      #ansible.builtin.apt_repository:
      #repo: ppa:giuspen/ppa

      #  - name: Add cryptomator ppa
      #ansible.builtin.apt_repository:
      #repo: ppa:sebastian-stenzel/cryptomator      

  - name: install htop
    package:
      name: 
        - inxi
        - curl
        - samba
        - vlc
        
          #- name: .bashrc file
    #copy:
            #src: files/bashrc
      #dest: '{{ user_directory }}/.bashrc'
      #owner: '{{ username }}'
      #    group: '{{ username }}' 

  - name: add ansible admin user
    user:
      name: ansible_admin
      system: yes

  - name: set sudo for ansible admin user
    copy:
      src: files/sudoers_ansible_admin
      dest: /etc/sudoers.d/ansible_admin
      owner: root
      group: root
      mode: 0440

  - name: add cronjob to pull changes in ansible repo
    cron:
      name: ansible auto-provision
      user: ansible_admin
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/p3t33/ansible_desktop.git  

# run roles
#
- hosts: localhost
  tags: base
  become: true
  roles:
    - base
  
- hosts: localhost
  tags: development
  become: true
  roles:
    - development
