
- name: users | kmedrish | create group
  tags: groups,kmedrish,users
  group:
    name: kmedrish
    state: present
  
- name: users | kmedrish | create user
  tags: kmedrish,sudo,users
  user:
    name: kmedrish
    group: kmedrish
    groups: adm,kmedrish,sudo 
    state: present
    shell: /bin/zsh

- name: Install oh-my-zsh
  become: true
  shell:
    cmd: "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"