
- name: users | kmedrish | create group
  tags: groups,kmedrish,users
  group:
    name: kmedrish
    state: present
  
- name: users | kmedrish | create user
  tags: kmedrish,sudo,users
  user:
    name: kmedrish
    group: kmedrish
    groups: adm,kmedrish,sudo 
    state: present
    shell: /bin/zsh