- name: install base packages
  package:
    name:
      - inxi
      - curl
      - samba
      - restic
      - zsh
      - syncthing

- name: set up zsh for user
  become: no
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh