- name: install base packages
  package:
    name:
      - inxi
      - curl
      - samba
      - restic
      - zsh
      - syncthing

- name: change user shell to zsh 
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/bash



