- name: install base packages
  package:
    name:
      - inxi
      - curl
      - samba
      - restic
      - zsh
      - syncthing

- name: set up zsh for user
  become: no
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh