- name: install base packages
  package:
    name:
      - inxi
      - curl
      - samba
      - restic
      - zsh
      - syncthing

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true