# Load distro-specific variables
#

- block:
  # configure user to pull on the repo
  - import_tasks: users/ansible_admin.yml

  # install basic usefull software
  - import_tasks: software/base_packages.yml
