# Load distro-specific variables
#

- block:
  # configure user to pull on the repo
  - import_tasks: software/add_repositories.yml

  # install packages
  - import_tasks: software/base_packages.yml

  # Configure system users
  # ----------------------

  #configure user to pull on the ansible repo
  - import_tasks: users/ansible_admin.yml

  #configure root for auto update
  - import_tasks: users/root.yml
  - import_tasks: users/kmedrish.yml


